<script>
    "use strict";
    window.config = {!! json_encode(array_merge([
      'url' => url('/'),
      'admin_url' => adminUrl(),
      'lang' => getLocale(),
      'direction' => getDirection(),
      'colors' => @$settings->system_admin->colors ?? ['primary_color' => '#1DA1F2', 'secondary_color' => '#000000'],
      'translates' => [
          'copied' => translate('Copied to clipboard'),
          'fillAllRequiredFields' => translate('Please fill all required fields'),
          'actionConfirm' => translate('Are you sure you want to perform this action?'),
          'emptyTable' => translate('No data available'),
          'searchPlaceholder' => translate('Start typing to search...'),
          'sLengthMenu' => translate('_MENU_'),
          'info' => translate('Showing _START_ to _END_ of _TOTAL_ totals'),
          'infoEmpty' => translate('Showing 0 to 0 of 0 entries'),
          'infoFiltered' => translate('(filtered from _MAX_ totals)'),
          'zeroRecords' => translate('No matching records found!'),
          'selectAtLeastOne' => translate('Please select at least one item'),
          'bulkActions' => translate('Bulk Actions'),
          'deleteSelected' => translate('Delete Selected'),
          'deleteSelectedError' => translate('Some selected items could not be deleted. Please try again later.'),
          'confirmBulkDelete' => translate('Are you sure you want to delete the selected items?'),
          'paginate' => [
              'first' => '<i class="bi bi-chevron-bar-left"></i>',
              'previous' => '<i class="bi bi-chevron-left"></i>',
              'next' => '<i class="bi bi-chevron-right"></i>',
              'last' => '<i class="bi bi-chevron-bar-right"></i>',
          ],
          'on' => translate('Enabled'),
          'off' => translate('Disabled'),
          'noneResultsText' => translate('No results found'),
          'countSelectedText' => translate('{0} of {1} selected'),
          'leaveUnsavedText' => translate('You have unsaved changes. Are you sure you want to leave?'),
          'Section Options' => translate('Section Options'),
          'Edit Details' => translate('Edit Details'),
          'Edit' => translate('Edit Details'),
          'Remove' => translate('Remove'),
          'Inactive' => translate('Inactive'),
          'Remove this block?' => translate('Remove this block?'),
          'This block is already added in this column.' => translate('This block is already added in this column.'),
          'Saving...' => translate('Saving...'),
          'Applying...' => translate('Applying...'),
          'Section settings applied' => translate('Section settings applied'),
          'Block settings saved' => translate('Block settings saved'),
          'Failed to load options' => translate('Failed to load options'),
          'Failed to load content' => translate('Failed to load content'),
          'Failed to update' => translate('Failed to update'),
          'Failed to update layout' => translate('Failed to update layout'),
          'Enabled' => translate('Enabled'),
          'Disabled' => translate('Disabled'),
          'Column' => translate('Column'),
          'Columns' => translate('Columns'),
          'Column Layout' => translate('Column Layout'),
          'Middle Alignment' => translate('Middle Alignment'),
          'Left' => translate('Left'),
          'Center' => translate('Center'),
          'Right' => translate('Right'),
          'Add New Section' => translate('Add New Section'),
          'Move Section' => translate('Move Section'),
          'Delete Section' => translate('Delete Section'),
          'Delete this section?' => translate('Delete this section?'),
          'Uploading...' => translate('Uploading...'),
          'Uploaded Image' => translate('Uploaded Image'),
          'Upload failed' => translate('Upload failed'),
          'New Item' => translate('New Item'),
          'Remove this item?' => translate('Remove this item?'),
          'Already added this block here.' => translate('Already added this block here.'),
      ],
  ], $customConfig ?? [])) !!}
</script>
